service: serverless-chime-reko

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
resources:
  Resources:
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs: 
          - arn:aws:cognito-idp:us-west-2:621170239250:userpool/us-west-2_PsC9h5W0N

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  
  start_meeting:
    handler: index.handler
    events:
      - http: 
          path: /meeting
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  face_recognition:
    handler: index.handler
    events:
      - http: 
          path: /face-recognition
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
